# Generated by Django 5.1.3 on 2024-11-08 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ejercicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_ejercicio", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=50)),
                ("dificultad", models.CharField(max_length=50)),
                ("descripcion", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_rol", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Rutina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_rutina", models.CharField(max_length=100)),
                ("objetivo", models.CharField(max_length=100)),
                ("tiempo_disponible", models.IntegerField()),
                ("ejercicios", models.ManyToManyField(to="core.ejercicio")),
            ],
        ),
        migrations.CreateModel(
            name="HistorialProgreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                ("repeticiones", models.IntegerField()),
                ("tiempo", models.IntegerField()),
                ("peso_usado", models.FloatField()),
                (
                    "ejercicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.ejercicio"
                    ),
                ),
                (
                    "rutina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.rutina"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("contraseña", models.CharField(max_length=100)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "rol",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.rol"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="rutina",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.usuario"
            ),
        ),
        migrations.CreateModel(
            name="Recomendacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recomendacion_texto", models.TextField()),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.usuario"
                    ),
                ),
            ],
        ),
    ]
