# Generated by Django 5.1.3 on 2024-11-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_recomendacion_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historialprogreso",
            name="tiempo",
            field=models.FloatField(),
        ),
    ]
